# Generated by Django 4.2 on 2024-04-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='名称')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('uuid', models.CharField(blank=True, default='', max_length=100, verbose_name='UUID')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Token')),
                ('status', models.CharField(blank=True, default='', max_length=25, verbose_name='状态')),
                ('droplet_limit', models.PositiveSmallIntegerField(default=0, verbose_name='配额')),
                ('month_to_date_balance', models.CharField(blank=True, default='', max_length=25, verbose_name='余额')),
                ('account_balance', models.CharField(blank=True, default='', max_length=25, verbose_name='余额')),
                ('month_to_date_usage', models.CharField(blank=True, default='', max_length=25, verbose_name='余额')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账号列表',
                'verbose_name_plural': '账号列表',
            },
        ),
        migrations.CreateModel(
            name='Droplets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droplet_id', models.IntegerField(verbose_name='实例ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='实例名称')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='公网IP')),
                ('memory', models.PositiveSmallIntegerField(default=0, verbose_name='内存大小')),
                ('vcpus', models.PositiveSmallIntegerField(default=0, verbose_name='CPU核心')),
                ('disk', models.PositiveSmallIntegerField(default=0, verbose_name='硬盘大小')),
                ('status', models.CharField(choices=[('active', '运行中'), ('pending', '启动中'), ('stopped', '已停止'), ('stopping', '停止中')], default='running', max_length=20, verbose_name='实例状态')),
                ('size_slug', models.CharField(blank=True, default='', max_length=50, verbose_name='实例规格')),
                ('image_slug', models.CharField(blank=True, default='', max_length=50, verbose_name='镜像ID')),
                ('region_slug', models.CharField(blank=True, default='', max_length=50, verbose_name='地区ID')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droplet_account', to='do.account', verbose_name='所属账号')),
            ],
            options={
                'verbose_name': '实例列表',
                'verbose_name_plural': '实例列表',
            },
        ),
    ]
