# Generated by Django 4.2 on 2024-04-29 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='订阅名称')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('subscription_id', models.CharField(blank=True, default='', max_length=100, verbose_name='订阅ID')),
                ('login_password', models.CharField(blank=True, default='', max_length=255, verbose_name='登录密码')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='APP_SECRET')),
                ('client_id', models.CharField(db_index=True, max_length=100, verbose_name='APP_ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100, verbose_name='TENANT')),
                ('update', models.BooleanField(default=0, verbose_name='是否升级')),
                ('status', models.CharField(blank=True, choices=[('Enabled', '正常'), ('Warned', '警告'), ('Disabled', '已停止')], default='', max_length=25, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='az_account', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账号管理',
                'verbose_name_plural': '账号管理',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='实例名称')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('vm_size', models.CharField(blank=True, default='', max_length=100, verbose_name='实例规格')),
                ('vm_id', models.CharField(blank=True, default='', max_length=100, verbose_name='实例ID')),
                ('image', models.CharField(blank=True, default='', max_length=100, verbose_name='系统名称')),
                ('os_disk', models.PositiveSmallIntegerField(default=0, verbose_name='系统盘')),
                ('nic_name', models.CharField(blank=True, default='', max_length=50, verbose_name='网络接口')),
                ('public_ip_name', models.CharField(blank=True, default='', max_length=50, verbose_name='公共IP')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='初始账号')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='初始密码')),
                ('status', models.CharField(blank=True, choices=[('stopping', '关机中'), ('stopped', '已关机'), ('running', '运行中'), ('Deleting', '删除中'), ('Creating', '创建中'), ('starting', '启动中')], default='', max_length=25, verbose_name='状态')),
                ('group', models.CharField(blank=True, default='', max_length=50, verbose_name='资源组名称')),
                ('location', models.CharField(blank=True, default='', max_length=25, verbose_name='地区')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='az_vm_account', to='azure.account', verbose_name='所属账号')),
            ],
            options={
                'verbose_name': '实例管理',
                'verbose_name_plural': '实例管理',
            },
        ),
    ]
