# Generated by Django 4.2 on 2024-04-29 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='名称')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('key_id', models.CharField(max_length=50, verbose_name='KeyID')),
                ('secret', models.CharField(max_length=100, verbose_name='Secret')),
                ('status', models.BooleanField(default=False, verbose_name='是否启用')),
                ('auto_boot', models.BooleanField(default=False, verbose_name='自动开机')),
                ('sale', models.BooleanField(default=False, verbose_name='是否销售')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('aga', models.BooleanField(default=False, verbose_name='支持AGA')),
                ('ec2', models.BooleanField(default=False, verbose_name='支持EC2')),
                ('value', models.PositiveSmallIntegerField(default=8, verbose_name='账号等级')),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='注册IP')),
                ('card', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='信用卡')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_users', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账号列表',
                'verbose_name_plural': '账号列表',
            },
        ),
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=200, verbose_name='实例名称')),
                ('public_ip', models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='公网IP')),
                ('private_ip', models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='内网IP')),
                ('region', models.CharField(default='', max_length=50, verbose_name='实例地区')),
                ('image_id', models.CharField(default='', max_length=50, verbose_name='镜像ID')),
                ('instance_type', models.CharField(default='', max_length=50, verbose_name='实例规格')),
                ('instance_id', models.CharField(db_index=True, default='', max_length=50, verbose_name='实例ID')),
                ('is_aga', models.BooleanField(default=False, verbose_name='支持AGA')),
                ('status', models.CharField(choices=[('running', '运行中'), ('pending', '启动中'), ('stopped', '已停止'), ('stopping', '停止中'), ('terminated', '已终止'), ('shutting-down', '正在关闭')], default='running', max_length=20, verbose_name='实例状态')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='实例密码')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('expire_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec2_account', to='aws.account', verbose_name='所属账号')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ec2_users', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'EC2',
                'verbose_name_plural': 'EC2',
            },
        ),
        migrations.CreateModel(
            name='Ec2Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='镜像名称')),
                ('ami', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='镜像ID')),
                ('region', models.CharField(default='', max_length=50, verbose_name='地区')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'EC2镜像',
                'verbose_name_plural': 'EC2镜像',
            },
        ),
        migrations.CreateModel(
            name='Lightsail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='实例名称')),
                ('public_ip', models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='公网IP')),
                ('private_ip', models.GenericIPAddressField(db_index=True, default='', verbose_name='内网IP')),
                ('location', models.TextField(default='{}', verbose_name='地区')),
                ('hardware', models.TextField(default='{}', verbose_name='硬件信息')),
                ('os_name', models.CharField(default='', max_length=50, verbose_name='系统名称')),
                ('os_id', models.CharField(default='', max_length=50, verbose_name='镜像ID')),
                ('bundle_id', models.CharField(default='', max_length=50, verbose_name='规格ID')),
                ('support_code', models.CharField(default='', max_length=50, verbose_name='支持代码')),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='实例密码')),
                ('status', models.CharField(choices=[('running', '运行中'), ('pending', '启动中'), ('stopped', '已停止'), ('stopping', '停止中')], default='running', max_length=20, verbose_name='实例状态')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('api', models.BooleanField(default=False, verbose_name='API接口')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('expire_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightsail_account', to='aws.account', verbose_name='所属账号')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lightsail_users', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '轻量主机',
                'verbose_name_plural': '轻量主机',
            },
        ),
        migrations.CreateModel(
            name='GlobalAccelerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arn', models.CharField(default='', max_length=255, unique=True, verbose_name='ARN')),
                ('ip_address', models.CharField(blank=True, default='', max_length=255, verbose_name='IP地址')),
                ('name', models.CharField(blank=True, default='-', max_length=200, verbose_name='实例名称')),
                ('dns_name', models.CharField(blank=True, default='-', max_length=200, verbose_name='域名')),
                ('status', models.CharField(choices=[('DEPLOYED', '部署完成'), ('IN_PROGRESS', '部署中')], default='IN_PROGRESS', max_length=20, verbose_name='实例状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aga_account', to='aws.account', verbose_name='所属账号')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aga_instance', to='aws.ec2', verbose_name='绑定实例')),
            ],
            options={
                'verbose_name': '全球加速器',
                'verbose_name_plural': '全球加速器',
            },
        ),
    ]
