# Generated by Django 4.2 on 2024-04-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='名称')),
                ('euuid', models.CharField(blank=True, max_length=50, verbose_name='uuid')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Token')),
                ('status', models.BooleanField(blank=True, default=True, max_length=25, verbose_name='状态')),
                ('balance', models.CharField(blank=True, default='', max_length=25, verbose_name='余额')),
                ('active_promotions', models.TextField(blank=True, default='', verbose_name='优惠详情')),
                ('note', models.CharField(blank=True, default='', max_length=50, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账户管理',
                'verbose_name_plural': '账户管理',
            },
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField(verbose_name='实例ID')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='名称')),
                ('status', models.CharField(blank=True, choices=[('shutting_down', '关机中'), ('provisioning', '创建中'), ('rebuilding', '重装中'), ('rebooting', '重启中'), ('deleting', '删除中'), ('running', '运行中'), ('booting', '启动中'), ('stopped', '已关机')], max_length=20, verbose_name='名称')),
                ('type', models.CharField(blank=True, choices=[('g6-nanode-1', '1vCPUs, 1GB RAM, 25GB DISK, $5'), ('g6-standard-1', '1vCPUs, 2GB RAM, 50GB DISK, $10'), ('g6-standard-2', '2vCPUs, 4GB RAM, 80GB DISK, $20'), ('g6-standard-4', '4vCPUs, 8GB RAM, 160GB DISK, $40'), ('g6-standard-6', '6vCPUs, 16GB RAM, 320GB DISK, $80'), ('g6-standard-8', '8vCPUs, 32GB RAM, 640GB DISK, $160'), ('g6-standard-16', '16vCPUs, 64GB RAM, 1280GB DISK, $320'), ('g6-standard-20', '20vCPUs, 96GB RAM, 1920GB DISK, $480'), ('g6-standard-24', '24vCPUs, 128GB RAM, 2560GB DISK, $640'), ('g6-standard-32', '32vCPUs, 192GB RAM, 3840GB DISK, $960'), ('g7-highmem-1', '2vCPUs, 24GB RAM, 20GB DISK, $60'), ('g7-highmem-2', '2vCPUs, 48GB RAM, 40GB DISK, $120'), ('g7-highmem-4', '4vCPUs, 90GB RAM, 90GB DISK, $240'), ('g7-highmem-8', '8vCPUs, 150GB RAM, 200GB DISK, $480'), ('g7-highmem-16', '16vCPUs, 300GB RAM, 340GB DISK, $960'), ('g6-dedicated-2', '2vCPUs, 4GB RAM, 80GB DISK, $30'), ('g6-dedicated-4', '4vCPUs, 8GB RAM, 160GB DISK, $60'), ('g6-dedicated-8', '8vCPUs, 16GB RAM, 320GB DISK, $120'), ('g6-dedicated-16', '16vCPUs, 32GB RAM, 640GB DISK, $240'), ('g6-dedicated-32', '32vCPUs, 64GB RAM, 1280GB DISK, $480'), ('g6-dedicated-48', '48vCPUs, 96GB RAM, 1920GB DISK, $720'), ('g6-dedicated-50', '50vCPUs, 128GB RAM, 2500GB DISK, $960'), ('g6-dedicated-56', '56vCPUs, 256GB RAM, 5000GB DISK, $1920'), ('g6-dedicated-64', '64vCPUs, 512GB RAM, 7200GB DISK, $3840'), ('g1-gpu-rtx6000-1', '8vCPUs, 32GB RAM, 640GB DISK, $1000'), ('g1-gpu-rtx6000-2', '16vCPUs, 64GB RAM, 1280GB DISK, $2000'), ('g1-gpu-rtx6000-3', '20vCPUs, 96GB RAM, 1920GB DISK, $3000'), ('g1-gpu-rtx6000-4', '24vCPUs, 128GB RAM, 2560GB DISK, $4000')], max_length=20, verbose_name='实例规格')),
                ('image', models.CharField(blank=True, choices=[('linode/almalinux8', 'AlmaLinux 8'), ('linode/almalinux9', 'AlmaLinux 9'), ('linode/alpine3.14', 'Alpine 3.14'), ('linode/alpine3.15', 'Alpine 3.15'), ('linode/alpine3.16', 'Alpine 3.16'), ('linode/alpine3.17', 'Alpine 3.17'), ('linode/alpine3.18', 'Alpine 3.18'), ('linode/arch', 'Arch Linux'), ('linode/centos7', 'CentOS 7'), ('linode/centos-stream8', 'CentOS Stream 8'), ('linode/centos-stream9', 'CentOS Stream 9'), ('linode/rocky8', 'Rocky Linux 8'), ('linode/rocky9', 'Rocky Linux 9'), ('linode/debian9', 'Debian 9'), ('linode/debian10', 'Debian 10'), ('linode/debian11', 'Debian 11'), ('linode/debian12', 'Debian 12'), ('linode/fedora36', 'Fedora 36'), ('linode/fedora37', 'Fedora 37'), ('linode/fedora38', 'Fedora 38'), ('linode/gentoo', 'Gentoo'), ('linode/kali', 'Kali Linux'), ('linode/debian11-kube-v1.25.4', 'Kubernetes 1.25.4 on Debian 11'), ('linode/debian11-kube-v1.26.1', 'Kubernetes 1.26.1 on Debian 11'), ('linode/debian11-kube-v1.26.3', 'Kubernetes 1.26.3 on Debian 11'), ('linode/debian11-kube-v1.27.5', 'Kubernetes 1.27.5 on Debian 11'), ('linode/opensuse15.4', 'openSUSE Leap 15.4'), ('linode/opensuse15.5', 'openSUSE Leap 15.5'), ('linode/slackware14.1', 'Slackware 14.1'), ('linode/slackware14.2', 'Slackware 14.2'), ('linode/slackware15.0', 'Slackware 15.0'), ('linode/ubuntu16.04lts', 'Ubuntu 16.04 LTS'), ('linode/ubuntu18.04', 'Ubuntu 18.04 LTS'), ('linode/ubuntu20.04', 'Ubuntu 20.04 LTS'), ('linode/ubuntu22.04', 'Ubuntu 22.04 LTS'), ('linode/ubuntu22.10', 'Ubuntu 22.10'), ('linode/ubuntu23.04', 'Ubuntu 23.04'), ('linode/ubuntu23.10', 'Ubuntu 23.10')], max_length=50, verbose_name='镜像地址')),
                ('region', models.CharField(blank=True, choices=[('jp-osa', '日本-大阪'), ('ap-northeast', '日本-东京'), ('ap-south', '新加坡'), ('ap-west', '印度'), ('eu-central', '德国'), ('ca-central', '加拿大'), ('ap-southeast', '澳大利亚'), ('eu-west', '英国-伦敦'), ('us-central', '美国中部-达拉斯'), ('us-west', '美国西部-费利蒙'), ('us-southeast', '美国南部-亚特兰大'), ('us-east', '美国东部-新泽西'), ('us-iad', '美国-华盛顿'), ('us-mia', '美国-迈阿密'), ('us-ord', '美国-芝加哥'), ('fr-par', '法国-巴黎'), ('us-sea', '美国-西雅图'), ('br-gru', '巴西-圣保罗'), ('nl-ams', '荷兰-阿姆斯特丹'), ('se-sto', '瑞典-斯德哥尔摩'), ('in-maa', '印度-清奈'), ('it-mil', '意大利-米兰'), ('id-cgk', '印尼-雅加达')], max_length=20, verbose_name='镜像地址')),
                ('ipv4', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IPV4')),
                ('ipv6', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IPV6')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ld_account', to='linode.account', verbose_name='所属账号')),
            ],
            options={
                'verbose_name': '实例管理',
                'verbose_name_plural': '实例管理',
            },
        ),
    ]
