# Generated by Django 4.2 on 2024-04-29 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='system', max_length=100, verbose_name='用户名')),
                ('title', models.CharField(db_index=True, default='', max_length=200, verbose_name='日志标题')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '其他'), (2, '阿里云')], default=1, verbose_name='日志类型')),
                ('content', models.TextField(default='', verbose_name='日志内容')),
                ('ip', models.GenericIPAddressField(db_index=True, default='', verbose_name='操作IP')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '公共日志',
                'verbose_name_plural': '公共日志',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='变量名称')),
                ('value', models.TextField(blank=True, default='', null=True, verbose_name='内容')),
                ('autoload', models.BooleanField(default=1, verbose_name='自动加载')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
                'db_table': 'hy_options',
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='脚本名称')),
                ('content', models.TextField(blank=True, default='', verbose_name='脚本内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('users', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='脚本')),
            ],
            options={
                'verbose_name': '脚本管理',
                'verbose_name_plural': '脚本管理',
            },
        ),
    ]
