[program:django-server]
command=gunicorn panelProject.wsgi:application --bind 0.0.0.0:8111 --workers 4 --timeout 120 --access-logfile /home/python/panel/logs/gunicorn-access.log --error-logfile /home/python/panel/logs/gunicorn-error.log
directory=/home/python/panel
user=root
autostart=true
autorestart=true
stdout_logfile=/home/python/panel/logs/django.log
stderr_logfile=/home/python/panel/logs/django.err
environment=PYTHONUNBUFFERED=1
